/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SumarmeRouteImport } from './routes/sumarme'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TSlugRouteImport } from './routes/t.$slug'

const SumarmeRoute = SumarmeRouteImport.update({
  id: '/sumarme',
  path: '/sumarme',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugRoute = TSlugRouteImport.update({
  id: '/t/$slug',
  path: '/t/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sobre': typeof SobreRoute
  '/sumarme': typeof SumarmeRoute
  '/t/$slug': typeof TSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sobre': typeof SobreRoute
  '/sumarme': typeof SumarmeRoute
  '/t/$slug': typeof TSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sobre': typeof SobreRoute
  '/sumarme': typeof SumarmeRoute
  '/t/$slug': typeof TSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sobre' | '/sumarme' | '/t/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sobre' | '/sumarme' | '/t/$slug'
  id: '__root__' | '/' | '/sobre' | '/sumarme' | '/t/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SobreRoute: typeof SobreRoute
  SumarmeRoute: typeof SumarmeRoute
  TSlugRoute: typeof TSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sumarme': {
      id: '/sumarme'
      path: '/sumarme'
      fullPath: '/sumarme'
      preLoaderRoute: typeof SumarmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug': {
      id: '/t/$slug'
      path: '/t/$slug'
      fullPath: '/t/$slug'
      preLoaderRoute: typeof TSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SobreRoute: SobreRoute,
  SumarmeRoute: SumarmeRoute,
  TSlugRoute: TSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
