version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: pp-mongo
    restart: unless-stopped
    ports: ["27017:27017"]
    volumes: [mongo_data:/data/db]
    healthcheck:
      test: ["CMD","mongosh","--quiet","--eval","db.adminCommand('ping').ok"]
      interval: 15s
      timeout: 5s
      retries: 10
    networks: [pp-net]

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: pp-sqlserver
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Your_strong_Passw0rd"
      MSSQL_PID: "Developer"
    ports: ["1433:1433"]
    volumes: [mssql_data:/var/opt/mssql]
    healthcheck:
      test: ["CMD-SHELL","/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P Your_strong_Passw0rd -No -Q 'SELECT 1' || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 15
      start_period: 40s
    networks: [pp-net]

  backend:
    build: ../back
    container_name: pp-backend
    restart: unless-stopped
    env_file: ../back/.env
    environment:
      MONGO_URI: mongodb://mongo:27017/provider_auth
      SQL_HOST: sqlserver
    depends_on:
      mongo: { condition: service_healthy }
      sqlserver: { condition: service_healthy }
    ports: ["4000:4000"]
    networks: [pp-net]

  frontend:
    build: ../front
    container_name: pp-frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:4000/api
    depends_on: [backend]
    ports: ["5173:5173"]
    networks: [pp-net]

volumes:
  mongo_data:
  mssql_data:

networks:
  pp-net:
    driver: bridge
